CREATE TABLE User(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    IP VARCHAR(30) UNIQUE NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE Service(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE User_Has_Service(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT UNSIGNED NOT NULL,
    SERVICE_ID INT UNSIGNED NOT NULL,
    
    FOREIGN KEY(USER_ID) REFERENCES User(ID),
    FOREIGN KEY(SERVICE_ID) REFERENCES Service(ID)

);

CREATE TABLE Ticket(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT UNSIGNED NOT NULL,
    SERVICE_ID INT UNSIGNED NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    
	FOREIGN KEY(USER_ID) REFERENCES User(ID),
    FOREIGN KEY(SERVICE_ID) REFERENCES Service(ID)
);

INSERT INTO USER(IP,PASSWORD) VALUES('127.0.0.0','password1');
INSERT INTO USER(IP,PASSWORD) VALUES('128.0.0.0','password2');
INSERT INTO USER(IP,PASSWORD) VALUES('129.0.0.0','password3');

INSERT INTO SERVICE(NAME) VALUES('SERVICE1');
INSERT INTO SERVICE(NAME) VALUES('SERVICE2');
INSERT INTO SERVICE(NAME) VALUES('SERVICE3');

INSERT INTO USER_HAS_SERVICE(USER_ID,SERVICE_ID) VALUES(1,1);
INSERT INTO USER_HAS_SERVICE(USER_ID,SERVICE_ID) VALUES(1,3);
INSERT INTO USER_HAS_SERVICE(USER_ID,SERVICE_ID) VALUES(1,4);

INSERT INTO USER_HAS_SERVICE(USER_ID,SERVICE_ID) VALUES(2,1);
INSERT INTO USER_HAS_SERVICE(USER_ID,SERVICE_ID) VALUES(2,3);

INSERT INTO USER_HAS_SERVICE(USER_ID,SERVICE_ID) VALUES(3,1);

COMMIT;